name: SketchTool Extract

on:
  push:
    branches:
    - master
    paths:
    - '**.sketch'

jobs:
  assets:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download & Install Sketch
      run: |
        curl -O https://download.sketchapp.com/sketch-60.1-88133.zip
        unzip sketch-60.1-88133.zip
    - name: Run SketchTool
      run: Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export layers sample-document.sketch
    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '*.png,*.svg,*.jpg,*.pdf'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: v1.0
