name: SketchTool Extract

on:
  push:
    branches:
    - master
    paths:
    - '**.sketch'

jobs:
  assets:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download & Install Sketch
      run: |
        curl -O https://download.sketchapp.com/sketch-60.1-88133.zip
        unzip sketch-60.1-88133.zip
    - name: Run SketchTool
      run: Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export layers sample-document.sketch
    - name: Update assets in assets folder
      uses: alexesprit/action-update-file@v0.1.0
      with:
        file-path: assets/*
        commit-msg: Update assets
        github-token: ${{ secrets.GITHUB_TOKEN }}
